#!/bin/sh
# Copyright (C) 2023 muink
#
OOKLA_SPEEDTEST='/usr/libexec/netspeedtest/speedtest'
SPEEDTEST_RESULT='/var/speedtest_result'
INIT_SCRIPT='/etc/init.d/netspeedtest'
# uci
CONFIG_NAME='netspeedtest'
NAMEDDSECTION='config'


command="$OOKLA_SPEEDTEST --accept-gdpr --accept-license --progress=no"

! pgrep -f "$command" >/dev/null || return 1

[ "$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_enabled)" == "1" ] && \
export ALL_PROXY=$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_protocol)://$(uci -q get $CONFIG_NAME.$NAMEDDSECTION.proxy_server)

echo "Testing" > "$SPEEDTEST_RESULT"
result=$($command | grep 'www.speedtest.net/result/' | sed -E 's|.+(://www.speedtest.net/\S+).*|https\1|;s|(\.png)$||')
[ -n "$result" ] && echo "$result" > "$SPEEDTEST_RESULT" || echo "Test failed" > "$SPEEDTEST_RESULT"
